---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-project
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /data/jenkins-project
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-project
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
